version: '3'
services:
#mssql docker
  zenithfit-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - zenithfitnet

  zenithfit-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:ZenithFit=Server=zenithfit-sql,1433;Database=3156;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 53194:80
    networks:
      - zenithfitnet
    links:
      - zenithfit-sql
    depends_on:
      - zenithfit-sql
      
networks:
  zenithfitnet:
    driver: bridge      